In [1]:
# indexing in array


In [4]:
import numpy as np

In [17]:
a = np.arange(1,10).reshape((3,3))

In [18]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
a[0]

array([1, 2, 3])

In [20]:
#To get sample 3,6,9

In [25]:
a[:,2:]

array([[3],
       [6],
       [9]])

In [26]:
# to get sammple 1,4,7


In [30]:
a[:,0]

array([1, 4, 7])

In [31]:
# To get 5,6,8,9

In [34]:
a[1:,1:]

array([[5, 6],
       [8, 9]])

In [35]:
# To get only 8 

In [40]:
a[2:,1]

array([8])