In [1]:
# add two , sub , multi , divide array

In [2]:
import numpy as np

In [22]:
a = np.arange(1,10).reshape((3,3))
b = np.arange(10,19).reshape((3,3))

In [19]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [25]:
np.add(a,b)

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [31]:
np.subtract(a,b)

array([[-9, -9, -9],
       [-9, -9, -9],
       [-9, -9, -9]])

In [32]:
np.multiply(a,b)

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

In [33]:
np.divide(a,b)

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ],
       [0.4375    , 0.47058824, 0.5       ]])