In [1]:
## To find min , max  of array

In [2]:
import numpy as np

In [3]:
a = np.arange(1,13).reshape((3,4))

In [4]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
np.min(a)


1

In [6]:
np.argmin(a)

0

In [7]:
np.max(a)

12

In [8]:
np.argmax(a)

11

In [9]:
np.min(a,axis=1)

array([1, 5, 9])

In [10]:
np.min(a,axis=0)

array([1, 2, 3, 4])

In [11]:
np.max(a,axis=1)

array([ 4,  8, 12])

In [12]:
np.max(a,axis=0)

array([ 9, 10, 11, 12])