In [1]:
import numpy as np

In [2]:
#Q1 Create a 3×3 numpy array of all False

In [3]:
np.zeros((2,3),dtype=bool)

array([[False, False, False],
       [False, False, False]])

In [4]:
#Q2 Extract all odd numbers from arr

In [5]:
a = np.arange(12)

In [6]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
odd = a[a%2 != 0]
odd

array([ 1,  3,  5,  7,  9, 11])

In [8]:
#Q3 Extract all even numbers from arr

In [9]:
even = a[a%2 == 0]
even

array([ 0,  2,  4,  6,  8, 10])

In [10]:
#Q4 Replace all odd numbers in arr with -1

In [11]:
a[a%2 != 0] = -1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1, 10, -1])

In [12]:
#Q5 Convert a 1D array to a 2D array with 2 rows

In [13]:
a1 = a.reshape((2,6))
a1

array([[ 0, -1,  2, -1,  4, -1],
       [ 6, -1,  8, -1, 10, -1]])

In [14]:
# Q6 Stack arrays a and b vertically

In [15]:
a2 = np.arange(1,9).reshape((2,4)) 
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
b1 = np.arange(12,20).reshape((2,4))
b1

array([[12, 13, 14, 15],
       [16, 17, 18, 19]])

In [17]:
np.vstack((a2,b1))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [18]:
#Q7 stack the arrays a and b horizontally.

In [19]:
np.hstack((a2,b1))

array([[ 1,  2,  3,  4, 12, 13, 14, 15],
       [ 5,  6,  7,  8, 16, 17, 18, 19]])

In [20]:
#Q8 Reverse the rows of a 2D array arr

In [21]:
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
a2[::-1]

array([[5, 6, 7, 8],
       [1, 2, 3, 4]])

In [23]:
#Q9 Reverse the columns of a 2D array arr

In [24]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
arr[:][::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [26]:
#Q10 Create blank array

In [27]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])