# Practice array



In [18]:
l=[1,2,3,4,5,6]

In [19]:
import numpy as np

In [20]:
a=np.array(l)

In [21]:
a

array([1, 2, 3, 4, 5, 6])

In [22]:
# To check the dimension of array

In [23]:
a.ndim


1

In [24]:
# To check the type of array

In [25]:
type(a)

numpy.ndarray

In [26]:
# To check the len of array

In [27]:
len(a)

6

In [28]:
# to check the shape

In [29]:
a.shape


(6,)

In [34]:
# To convert the array into 2d array

In [35]:
a.reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
# To convert array into 3d array

In [37]:
a.reshape((3,1,2))

array([[[1, 2]],

       [[3, 4]],

       [[5, 6]]])

In [38]:
# To convert array into 3d to 1d


In [40]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [41]:
# to calculate mean

In [43]:
a.mean()

3.5

In [44]:
# To calculate variance

In [45]:
a.var()


2.9166666666666665

In [46]:
# To calculate standardeviation

In [47]:
a.std()

1.707825127659933